# Generated by Django 5.2.7 on 2025-10-28 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
