// Mocks generated by Mockito 5.4.6 from annotations
// in chaos_contained/test/screens/conversation_history_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chaos_contained/models/memory.dart' as _i2;
import 'package:chaos_contained/services/memory_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMemorySearchResult_0 extends _i1.SmartFake
    implements _i2.MemorySearchResult {
  _FakeMemorySearchResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMemory_1 extends _i1.SmartFake implements _i2.Memory {
  _FakeMemory_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryService extends _i1.Mock implements _i3.MemoryService {
  MockMemoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Memory>> getMemories({
    DateTime? startDate,
    DateTime? endDate,
    double? minRelevance,
    String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMemories, [], {
              #startDate: startDate,
              #endDate: endDate,
              #minRelevance: minRelevance,
              #role: role,
            }),
            returnValue: _i4.Future<List<_i2.Memory>>.value(<_i2.Memory>[]),
          )
          as _i4.Future<List<_i2.Memory>>);

  @override
  _i4.Future<_i2.MemorySearchResult> searchMemories(
    String? query, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchMemories, [query], {#limit: limit}),
            returnValue: _i4.Future<_i2.MemorySearchResult>.value(
              _FakeMemorySearchResult_0(
                this,
                Invocation.method(#searchMemories, [query], {#limit: limit}),
              ),
            ),
          )
          as _i4.Future<_i2.MemorySearchResult>);

  @override
  _i4.Future<void> cleanupOldMemories() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldMemories, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Memory> storeMemory({
    required String? message,
    required String? role,
    required Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#storeMemory, [], {
              #message: message,
              #role: role,
              #context: context,
            }),
            returnValue: _i4.Future<_i2.Memory>.value(
              _FakeMemory_1(
                this,
                Invocation.method(#storeMemory, [], {
                  #message: message,
                  #role: role,
                  #context: context,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Memory>);

  @override
  _i4.Future<bool> deleteMemory(int? memoryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMemory, [memoryId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.Memory>> queryRelevantMemories({
    required String? query,
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryRelevantMemories, [], {
              #query: query,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Memory>>.value(<_i2.Memory>[]),
          )
          as _i4.Future<List<_i2.Memory>>);
}
