// Mocks generated by Mockito 5.4.6 from annotations
// in chaos_contained/test/screens/focus_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chaos_contained/services/music_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MusicService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicService extends _i1.Mock implements _i2.MusicService {
  MockMusicService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.MusicProvider?> getActiveProvider() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveProvider, []),
            returnValue: _i3.Future<_i2.MusicProvider?>.value(),
          )
          as _i3.Future<_i2.MusicProvider?>);

  @override
  _i3.Future<void> connectProvider(_i2.MusicProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#connectProvider, [provider]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isConnected(_i2.MusicProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, [provider]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> disconnect(_i2.MusicProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [provider]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> next() =>
      (super.noSuchMethod(
            Invocation.method(#next, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> previous() =>
      (super.noSuchMethod(
            Invocation.method(#previous, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setMode, [mode]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
