# Generated by Django 5.2.7 on 2025-10-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model('users', 'User').objects.filter(
                    preferences__isnull=True
                ).update(preferences={
                    'voice': {
                        'enabled': True,
                        'useHeadphones': False,
                        'volume': 0.75,
                        'speed': 1.0,
                        'voice_id': 'default',
                        'background_enabled': True,
                        'background_volume': 0.3
                    },
                    'memory': {
                        'context_window': 10,
                        'memory_retention_days': 30,
                        'include_emotions': True,
                        'save_voice_clips': False,
                        'personalization_level': 'balanced'
                    },
                    'notifications': {
                        'voice_enabled': True,
                        'text_enabled': True,
                        'quiet_hours_start': '22:00',
                        'quiet_hours_end': '07:00'
                    }
                })
            ),
            reverse_code=lambda apps, schema_editor: None
        )
    ]
