// Mocks generated by Mockito 5.4.6 from annotations
// in chaos_contained/test/services/music_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chaos_contained/services/api_service.dart' as _i5;
import 'package:dio/dio.dart' as _i3;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIOSOptions_0 extends _i1.SmartFake implements _i2.IOSOptions {
  _FakeIOSOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_1 extends _i1.SmartFake
    implements _i2.AndroidOptions {
  _FakeAndroidOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_2 extends _i1.SmartFake implements _i2.LinuxOptions {
  _FakeLinuxOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_3 extends _i1.SmartFake
    implements _i2.WindowsOptions {
  _FakeWindowsOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_4 extends _i1.SmartFake implements _i2.WebOptions {
  _FakeWebOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_5 extends _i1.SmartFake implements _i2.MacOsOptions {
  _FakeMacOsOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_6<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i2.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_0(this, Invocation.getter(#iOptions)),
          )
          as _i2.IOSOptions);

  @override
  _i2.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_1(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i2.AndroidOptions);

  @override
  _i2.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_2(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i2.LinuxOptions);

  @override
  _i2.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_3(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i2.WindowsOptions);

  @override
  _i2.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_4(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i2.WebOptions);

  @override
  _i2.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_5(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i2.MacOsOptions);

  @override
  _i4.Future<void> write({
    required String? key,
    required String? value,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> read({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> containsKey({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> delete({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String>> readAll({
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<void> deleteAll({
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveTokens(String? access, String? refresh) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [access, refresh]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.Response<dynamic>> register(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#register, [data]),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(#register, [data]),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> login(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#login, [data]),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(this, Invocation.method(#login, [data])),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(this, Invocation.method(#getTasks, [])),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> createTask(Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [payload]),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(#createTask, [payload]),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> generateSchedule(
    Map<String, dynamic>? payload,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateSchedule, [payload]),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(#generateSchedule, [payload]),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> aiChat(Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
            Invocation.method(#aiChat, [payload]),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(#aiChat, [payload]),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> get(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#get, [path]),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(this, Invocation.method(#get, [path])),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> post(
    String? path, {
    dynamic data,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [path], {#data: data, #options: options}),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {#data: data, #options: options},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> put(
    String? path, {
    dynamic data,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path], {#data: data, #options: options}),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {#data: data, #options: options},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> delete(
    String? path, {
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path], {#options: options}),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(#delete, [path], {#options: options}),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);
}
